# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arhiva < Formula
  desc "Fast Miller-columns file manager for the terminal"
  homepage "https://github.com/aleksandargosevski/arhiva"
  version "1.0.2"
  license "MIT"

  depends_on "zoxide" => :optional
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aleksandargosevski/arhiva/releases/download/v1.0.2/arhiva_1.0.2_darwin_amd64.tar.gz"
    sha256 "01dea94eaf7f0d437561caa8e92571f823af61c1c4d2b608bc3200146249297f"

    define_method(:install) do
      bin.install "arhiva"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aleksandargosevski/arhiva/releases/download/v1.0.2/arhiva_1.0.2_darwin_arm64.tar.gz"
    sha256 "6bc7bef2f0770bd43872c8752ad345ebc0342fa02549c6ddc22ffa2b912c01ee"

    define_method(:install) do
      bin.install "arhiva"
    end
  end

  def caveats
    <<~EOS
      For cd on quit, add to ~/.zshrc:
        a() {
          local tmp="$(mktemp -t arhiva)"
          arhiva --cd-file="$tmp" "$@"
          local dir="$(cat "$tmp")"
          rm -f "$tmp"
          [ -n "$dir" ] && [ "$dir" != "$PWD" ] && cd "$dir"
        }
    EOS
  end

  test do
    system "#{bin}/arhiva", "--version"
  end
end
