# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arhiva < Formula
  desc "Fast Miller-columns file manager for the terminal"
  homepage "https://github.com/aleksandargosevski/arhiva"
  version "1.0.6"
  license "MIT"

  depends_on "zoxide" => :optional
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aleksandargosevski/arhiva/releases/download/v1.0.6/arhiva_1.0.6_darwin_amd64.tar.gz"
    sha256 "f970d32a607ec35bc1adb7b4001db14d5000e9de54a2d381321e82798a9312d6"

    define_method(:install) do
      bin.install "arhiva"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aleksandargosevski/arhiva/releases/download/v1.0.6/arhiva_1.0.6_darwin_arm64.tar.gz"
    sha256 "1f06269e513c4c4b409ac4996434760bb7e7df1ae9f56209f734123cd8c0f36b"

    define_method(:install) do
      bin.install "arhiva"
    end
  end

  def caveats
    <<~EOS
      For cd on quit, add to ~/.zshrc:
        a() {
          local tmp="$(mktemp -t arhiva)"
          arhiva --cd-file="$tmp" "$@"
          local dir="$(cat "$tmp")"
          rm -f "$tmp"
          [ -n "$dir" ] && [ "$dir" != "$PWD" ] && cd "$dir"
        }
    EOS
  end

  test do
    system "#{bin}/arhiva", "--version"
  end
end
