# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arhiva < Formula
  desc "Fast Miller-columns file manager for the terminal"
  homepage "https://github.com/aleksandargosevski/arhiva"
  version "1.0.3"
  license "MIT"

  depends_on "zoxide" => :optional
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aleksandargosevski/arhiva/releases/download/v1.0.3/arhiva_1.0.3_darwin_amd64.tar.gz"
    sha256 "f662def77f01e70998daf6a75b752697fe95ea542a96d0075488715eb1ab8c92"

    define_method(:install) do
      bin.install "arhiva"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aleksandargosevski/arhiva/releases/download/v1.0.3/arhiva_1.0.3_darwin_arm64.tar.gz"
    sha256 "023c916bbeb885ce8c7b54cbeede1ebb1caedbaa9fd89e532d30e51003798069"

    define_method(:install) do
      bin.install "arhiva"
    end
  end

  def caveats
    <<~EOS
      For cd on quit, add to ~/.zshrc:
        a() {
          local tmp="$(mktemp -t arhiva)"
          arhiva --cd-file="$tmp" "$@"
          local dir="$(cat "$tmp")"
          rm -f "$tmp"
          [ -n "$dir" ] && [ "$dir" != "$PWD" ] && cd "$dir"
        }
    EOS
  end

  test do
    system "#{bin}/arhiva", "--version"
  end
end
