# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hx < Formula
  desc "A fast shell history manager with fuzzy search, templates, and analytics"
  homepage "https://github.com/aleksandargosevski/hx"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksandargosevski/hx/releases/download/v0.1.0/hx_0.1.0_darwin_amd64.tar.gz"
      sha256 "83ab7c3d4df53e26aea2ee6a608542c10a1908f4dd99102f59a1031e045e14b6"

      define_method(:install) do
        bin.install "hx"
        generate_completions_from_executable(bin/"hx", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksandargosevski/hx/releases/download/v0.1.0/hx_0.1.0_darwin_arm64.tar.gz"
      sha256 "1166d182d21925c6b4d9e9161b47958a9b20ceb9f1b9debbe45b2931205c5b8b"

      define_method(:install) do
        bin.install "hx"
        generate_completions_from_executable(bin/"hx", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandargosevski/hx/releases/download/v0.1.0/hx_0.1.0_linux_amd64.tar.gz"
      sha256 "c8e08fe3f8dab8a3bb4703f00ab0a943049d61f863a700ae93fc313dd259b3bf"
      define_method(:install) do
        bin.install "hx"
        generate_completions_from_executable(bin/"hx", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandargosevski/hx/releases/download/v0.1.0/hx_0.1.0_linux_arm64.tar.gz"
      sha256 "4d2c5ff98271b8f2f806a315d142140cc61b8499260e3365fc1800ce58352ebf"
      define_method(:install) do
        bin.install "hx"
        generate_completions_from_executable(bin/"hx", "completion")
      end
    end
  end

  test do
    system "#{bin}/hx", "version"
  end
end
