# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skocko < Formula
  desc "Smart tmux session manager with a built-in TUI picker"
  homepage "https://github.com/aleksandargosevski/skocko"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_darwin_amd64.tar.gz"
      sha256 "ab37d427e762123d4f092a85ba35a696137d926edad6c23e2181029b71450e11"

      define_method(:install) do
        bin.install "skocko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_darwin_arm64.tar.gz"
      sha256 "1e82c55f2feb33557050c321ad5b4b64c604299d22d8f6ce9a977ff256ca7501"

      define_method(:install) do
        bin.install "skocko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_linux_amd64.tar.gz"
      sha256 "57ee4618b490dc4cef6c94f39324de72ccf1e5a042d9cf5599e4f7e632d7804e"
      define_method(:install) do
        bin.install "skocko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_linux_arm64.tar.gz"
      sha256 "efaa7f8fddaa87b0648b17a3bafc011f314f21fd60c68b53c4d8f98bc48fe3e0"
      define_method(:install) do
        bin.install "skocko"
      end
    end
  end

  test do
    system bin/"skocko", "--help"
  end
end
