# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skocko < Formula
  desc "Smart tmux session manager with a built-in TUI picker"
  homepage "https://github.com/aleksandargosevski/skocko"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_darwin_amd64.tar.gz"
      sha256 "d6bffb0050e1a486e5c1ae46e677635dcf5710ae6068718dba17c50b244a454a"

      define_method(:install) do
        bin.install "skocko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_darwin_arm64.tar.gz"
      sha256 "fac5df78130b77fed441e10a4e1db3ef0c1fd227b5af64b9fe46dce92f5e1318"

      define_method(:install) do
        bin.install "skocko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_linux_amd64.tar.gz"
      sha256 "a9267453e6a070fa6918afa9cbe24783ae75c5522c390d20a57b6c1d3469d143"
      define_method(:install) do
        bin.install "skocko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_linux_arm64.tar.gz"
      sha256 "3f612453353376cedb8b3e722e003d7bf5565b39c9b5ba809b3259410db3937b"
      define_method(:install) do
        bin.install "skocko"
      end
    end
  end

  test do
    system bin/"skocko", "--help"
  end
end
