# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skocko < Formula
  desc "Smart tmux session manager with a built-in TUI picker"
  homepage "https://github.com/aleksandargosevski/skocko"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_darwin_amd64.tar.gz"
      sha256 "741c9b90f0fe076b9c3b8d99c02c157ca7018cc75ee3140f2ee08016cb0d5d1a"

      define_method(:install) do
        bin.install "skocko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_darwin_arm64.tar.gz"
      sha256 "47bf55e678656753a200ae72167ac0b81e5aeda3d082c33d484f298727985075"

      define_method(:install) do
        bin.install "skocko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_linux_amd64.tar.gz"
      sha256 "fd0872a645c76e41f71bf5a9f259a7c176f438beec9eaca6a974501ac16fda4b"
      define_method(:install) do
        bin.install "skocko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksandargosevski/skocko/releases/download/v0.1.0/skocko_linux_arm64.tar.gz"
      sha256 "72ff24a22a3d037f5bebf0d6dcd78ddbebea21598af1499fcb4ea67ae6166ad7"
      define_method(:install) do
        bin.install "skocko"
      end
    end
  end

  test do
    system bin/"skocko", "--help"
  end
end
